### ISSUE TITLE
Backend Planning

### ISSUE THREAD

**Issue by hedi-far** [hedi-far/nextjs-kids-clothing-storage-web-app#5]
## General
- [x] Plan database schema: Clothing Database, User administration ... 
- [x] CASCADE on delete?!
- [x] Think of data structures - What is supposed to happen with the information? How is it supposed to be processed?
- [x] Plan SQL queries!!!

SQL queries: 

- https://www.db-fiddle.com/f/FosFgdEtRkz2HZLgFyQnS/0

Database schema: 

- https://app.sqldbm.com/PostgreSQL/Edit/p137762/

- [x] Which elements/ideas/processes can I re-use form former projects?

![image](https://user-images.githubusercontent.com/66747385/97687887-ffde2880-1a99-11eb-9aa9-6b09fa68ccdb.png)

## User administration

- [x] Seperate table for users
- [x] Seperate table for sessions 
- Users have possibility to delete their account. 
- [x] What happens after they delete their account? 
	- Get back to start page!
- [x] What happens in database when the users delete their account? 
	- Cascade ...(?)

## User Authentication

- [x] How can users login to the page?
- [x] How can they log out?
- [x] How is the session stored?
- [x] How is the session terminated?

### Create 
- [x] How will users be able to get information INTO the database?
	 They will enter the information via a form. 
	- [x] Which fields will the form have? 
		This depends on database schema.
	- [x] Will users be restricted to fixed terms (such as "shirt", "sweater", or will they be able to put in 			 			their own categories?)
	- [x] Validate forms to prevent SQL injections?
- [x] How will data be stored inside database technically? 
	- POST request? 

### Read
- How will users be able to get information OUT of the database?

	#### Dashboard - Overview:
	- They will see all the data they have entered so far on their dashboard.
	- e.g. "Bag 1" - list: 1 shirt size 92, 2 pants size 93
	- Dropdown-kind of thing (- as in bog posts - "Read on")
	- [x] Go to seperate page for each storage unit? - Probably not.

- [x] How will this information be sorted? 
	- Will users be able to re-sort their information? - 
	- Probably not. Just static list.

	#### Search function:
	- This should be a seperate page. 
	- Users should be able to find items that have specific according to specific features, 
		e.g. find all T-Shirts inside Box 1 that have size 92 (see also feature planning).
	- Can users enter their own search terms or are they restricted to given keywords (more like a filter 			 			 
      function)?
	- How are the search results displayed? 
	- How will it be possible to add them to a new dataset which will be then added to a final list? 
	- Will it  be possible to edit this list? 	

### Update
- [x] Which ways to edit data? 
- [x] Click on edit button next to specific item. 

### Delete
- Delete dataset (e.g. entire box/bag - single item)

## Stretch goal: GraphQL

- Use GraphQL to send information between React and the backend.

## Strech goal: Typescript

-  Write at least two pages and two components in Typescript.

**Comment by karlhorky** [comment]
@hedi-far as promised, here's a screenshot of your database schema on SqlDBM:

![Screen Shot 2020-11-11 at 16 35 31](https://user-images.githubusercontent.com/1935696/98833563-7ab22680-243e-11eb-89a4-4ffacee36b28.png)
